name: Upload file
on:
  push:
    branches:
    - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
     steps:
      - uses: actions/checkout@main
        env:
          AWS_S3_BUCKET: 'github-satish'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
      
