name: Terraform Apply
on: 
  push:
    branches:
     - main
jobs:
  terraform_apply:
    runs-on: centos-latest
    steps:
    - uses: actions/checkout@main
      env: |
       sudo yum install -y yum-utils
       sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
       sudo yum -y install terraform
