name: Upload file

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: Satishnimmana/github-actions-demo@main
    - name: Setup node
      uses: actions/setup-node@v2
     - name: Install dependencies
       run: npm install
     - name: Build static file
       run: npm run build
      with:
        args: --acl public-read --follow-symlinks --delete  --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: 'github-satish'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
      
