name: Terraform Apply
on: 
  push:
    branches:
     - main
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install Terraform
       env:
        lsb_release : "1.1.6"
       run: |
         curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
         sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
         sudo apt-get update && sudo apt-get install terraform
         sudo mv terraform /usr/local/bin/
